export enum LoadingKind {
  UNDEFINED = "UNDEFINED",
  LOADING = "LOADING",
  AUTHENTICATED = "AUTHENTICATED",
  IS_VERIFICATION_CHECKED_FALSE = "IS_VERIFICATION_CHECKED_FALSE",
  IS_CHECKING = "IS_CHECKING",
  ELSE = "ELSE",
}